---
abstract: 'Auto fill test names from caller line'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Name-FromLine
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Slurp: 0
  Filter::Util::Call: 0
  Test::Builder: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/Test-Name-FromLine
version: 0.02
